### ISSUE TITLE
DXP v22.10.0

### ISSUE THREAD

**Issue by meeximum** [neptune-software/p9-docker-compose-examples#1]
Hi,

is there a plan to build a compose file for the newest release?
I tried to use the 21.10.0 as base, but get an DB error when runnint compuse-up (I just changed the image version of the neptune DXP image)

regards
Meex

**Comment by txtmode** [comment]
Being fixed in this PR: https://github.com/neptune-software/dxp-open-edition-docker-compose-examples/pull/3

**Comment by txtmode** [comment]
Fixed and also updated for latest v22 and v23 patches
